"""Named subagents for the Reasoning vs Questioning challenge (10 Memory Slots).

Implementation lives in ``agents/ten_agents.py``. This module re-exports the
public API so existing imports (`from subagents import ...`) keep working.

Referee note: remote GitHub had only ``main`` (no Eric Schmidt branch/PR).
Elon Musk developed the 10 slot agents under Scott Weeden's advice.
"""

from __future__ import annotations

from agents.ten_agents import (
    MAX_SUBAGENT_QUEUE,
    OVERFLOW_AGENT_CLASSES,
    SUBAGENT_CLASSES,
    TEN_AGENT_CLASSES,
    AgronomyYieldAgent,
    AgronomyYieldSubagent,
    AntigravityAgent,
    AntigravitySubagent,
    DarioAmodeiAgent,
    DarioAmodeiSubagent,
    ElonMuskAgent,
    ElonMuskSubagent,
    EricSchmidtAgent,
    EricSchmidtSubagent,
    LaborOptimizationAgent,
    LaborOptimizationSubagent,
    LandExpansionAgent,
    LandExpansionSubagent,
    LivestockCareAgent,
    LivestockCareSubagent,
    MarketLiquidityAgent,
    MarketLiquiditySubagent,
    ScottWeedenAgentSlot,
    ScottWeedenSubagent,
    SubmissionPackagingAgent,
    SubmissionPackagingSubagent,
    SubagentQueue10,
    TenAgentQueue,
    assign_agronomy_yield,
    assign_antigravity,
    assign_dario_amodei,
    assign_elon_musk,
    assign_eric_schmidt,
    assign_labor_optimization,
    assign_land_expansion,
    assign_livestock_care,
    assign_market_liquidity,
    assign_scott_weeden,
    assign_submission_packaging,
    build_all_10_subagents,
)

__all__ = [
    "MAX_SUBAGENT_QUEUE",
    "SUBAGENT_CLASSES",
    "TEN_AGENT_CLASSES",
    "AgronomyYieldAgent",
    "AgronomyYieldSubagent",
    "AntigravityAgent",
    "AntigravitySubagent",
    "ElonMuskAgent",
    "ElonMuskSubagent",
    "EricSchmidtAgent",
    "EricSchmidtSubagent",
    "LaborOptimizationAgent",
    "LaborOptimizationSubagent",
    "LandExpansionAgent",
    "LandExpansionSubagent",
    "LivestockCareAgent",
    "LivestockCareSubagent",
    "MarketLiquidityAgent",
    "MarketLiquiditySubagent",
    "ScottWeedenAgentSlot",
    "ScottWeedenSubagent",
    "SubmissionPackagingAgent",
    "SubmissionPackagingSubagent",
    "SubagentQueue10",
    "TenAgentQueue",
    "assign_agronomy_yield",
    "assign_antigravity",
    "assign_elon_musk",
    "assign_eric_schmidt",
    "assign_labor_optimization",
    "assign_land_expansion",
    "assign_livestock_care",
    "assign_market_liquidity",
    "assign_scott_weeden",
    "assign_submission_packaging",
    "build_all_10_subagents",
]
